/**
 * Storage module — reads/writes idea reports as markdown files.
 * Ported from Python storage.py.
 */

import fs from 'fs';
import path from 'path';
import type { QA, PersonaCritique, Scores, DecisionArtifact } from '../types';

const IDEAS_DIR = path.join(process.cwd(), 'ideas');

// ── Slugify ────────────────────────────────────────────────────────

export function slugify(text: string, maxWords = 6): string {
  let slug = text
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '');
  const words = slug.split(/\s+/).slice(0, maxWords);
  slug = words.join('-').replace(/-+/g, '-').replace(/^-|-$/g, '');
  return slug || 'idea';
}

// ── Frontmatter ────────────────────────────────────────────────────

const FRONTMATTER_RE = /^---\n([\s\S]*?)\n---\n/;

export function parseFrontmatter(markdown: string): Record<string, string> {
  const m = markdown.match(FRONTMATTER_RE);
  if (!m) return {};
  const out: Record<string, string> = {};
  for (const line of m[1].split('\n')) {
    if (line.includes(':')) {
      const idx = line.indexOf(':');
      const k = line.slice(0, idx).trim();
      const v = line.slice(idx + 1).trim();
      out[k] = v;
    }
  }
  return out;
}

// ── Render report to markdown ──────────────────────────────────────

function averageScore(scores: Scores): number {
  return (
    (scores.tam +
      scores.competitive_density +
      scores.moat +
      scores.founder_fit +
      scores.why_now +
      scores.capital_efficiency) /
    6
  );
}

export function renderReport(report: {
  idea: string;
  title: string;
  slug: string;
  created: string;
  interview: QA[];
  market: string;
  competitors: string;
  critiques: PersonaCritique[];
  synthesis: string;
  decision: DecisionArtifact | null;
}): string {
  const lines: string[] = [];
  const decision = report.decision;
  const scoreAvg = decision ? `${averageScore(decision.scores).toFixed(1)}/10` : 'n/a';
  const rec = decision ? decision.recommendation : 'pending';

  lines.push('---');
  lines.push(`title: ${report.title}`);
  lines.push(`slug: ${report.slug}`);
  lines.push(`date: ${report.created}`);
  lines.push(`score: ${scoreAvg}`);
  lines.push(`recommendation: ${rec}`);
  lines.push('---');
  lines.push('');
  lines.push(`# ${report.title}`);
  lines.push('');
  lines.push(`**Date:** ${report.created}  `);
  lines.push(`**Score:** ${scoreAvg}  `);
  lines.push(`**Recommendation:** ${rec}`);
  lines.push('');
  lines.push('## Idea');
  lines.push('');
  lines.push(report.idea.trim());
  lines.push('');

  if (report.interview.length > 0) {
    lines.push('## Clarifying questions');
    lines.push('');
    for (let i = 0; i < report.interview.length; i++) {
      const qa = report.interview[i];
      lines.push(`**${i + 1}. ${qa.question.trim()}**`);
      lines.push('');
      lines.push(qa.answer.trim() || '_(skipped)_');
      lines.push('');
    }
  }

  if (report.market) {
    lines.push('## Market analysis');
    lines.push('');
    lines.push(report.market.trim());
    lines.push('');
  }

  if (report.competitors) {
    lines.push('## Competitor scan');
    lines.push('');
    lines.push(report.competitors.trim());
    lines.push('');
  }

  if (report.critiques.length > 0) {
    lines.push('## Multi-persona critique');
    lines.push('');
    for (const c of report.critiques) {
      lines.push(`### ${c.persona}`);
      lines.push('');
      lines.push(c.content.trim());
      lines.push('');
    }
  }

  if (report.synthesis) {
    lines.push('### Synthesis');
    lines.push('');
    lines.push(report.synthesis.trim());
    lines.push('');
  }

  if (decision) {
    lines.push('## Decision artifact');
    lines.push('');
    lines.push('### Scores (1-10)');
    lines.push('');
    const s = decision.scores;
    lines.push(`- TAM: ${s.tam}`);
    lines.push(`- Competitive density: ${s.competitive_density}`);
    lines.push(`- Moat: ${s.moat}`);
    lines.push(`- Founder-fit: ${s.founder_fit}`);
    lines.push(`- Why-now timing: ${s.why_now}`);
    lines.push(`- Capital efficiency: ${s.capital_efficiency}`);
    lines.push(`- **Average: ${averageScore(s).toFixed(1)}/10**`);
    lines.push('');
    lines.push('### Kill criteria');
    lines.push('');
    for (const k of decision.kill_criteria) {
      lines.push(`- ${k.trim()}`);
    }
    lines.push('');
    lines.push('### Cheapest validation experiment');
    lines.push('');
    lines.push(decision.validation_experiment.trim());
    lines.push('');
    lines.push('### Recommendation');
    lines.push('');
    lines.push(`**${decision.recommendation}** — ${decision.rationale.trim()}`);
    lines.push('');
  }

  lines.push('---');
  lines.push(`_Generated by idea-enhancer on ${new Date().toISOString().slice(0, 19)}_`);
  lines.push('');

  return lines.join('\n');
}

// ── Write report to disk ───────────────────────────────────────────

export function writeReport(
  report: {
    idea: string;
    title: string;
    slug: string;
    created: string;
    interview: QA[];
    market: string;
    competitors: string;
    critiques: PersonaCritique[];
    synthesis: string;
    decision: DecisionArtifact | null;
  },
  root?: string
): string {
  const dir = root || IDEAS_DIR;
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  const filename = `${report.created}-${report.slug}.md`;
  const filePath = path.join(dir, filename);
  fs.writeFileSync(filePath, renderReport(report), 'utf-8');
  return filename;
}

// ── List reports ───────────────────────────────────────────────────

export function listReports(root?: string): Array<Record<string, string>> {
  const dir = root || IDEAS_DIR;
  if (!fs.existsSync(dir)) return [];
  const out: Array<Record<string, string>> = [];
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.md')).sort();
  for (const file of files) {
    const text = fs.readFileSync(path.join(dir, file), 'utf-8');
    const meta = parseFrontmatter(text);
    meta['path'] = file;
    meta['body'] = text;
    out.push(meta);
  }
  return out;
}

// ── Read a single report ───────────────────────────────────────────

export function readReport(filename: string, root?: string): string | null {
  const dir = root || IDEAS_DIR;
  const filePath = path.join(dir, filename);
  if (!fs.existsSync(filePath)) return null;
  return fs.readFileSync(filePath, 'utf-8');
}

export function findReportBySlug(slug: string, root?: string): Record<string, string> | null {
  const reports = listReports(root);
  const matches = reports.filter((r) => r['slug']?.startsWith(slug));
  if (matches.length === 1) return matches[0];
  return null;
}
