from __future__ import annotations

import logging
import re
from datetime import date, datetime
from pathlib import Path

from idea_enhancer.models import (
    DecisionArtifact,
    PersonaCritique,
    QA,
    Report,
    Scores,
)

logger = logging.getLogger("idea_enhancer")

# Use project-root relative path when possible, fall back to CWD-relative.
_PROJECT_ROOT = Path(__file__).resolve().parents[3]  # src/idea_enhancer/ → repo root
IDEAS_DIR = _PROJECT_ROOT / "ideas"


def slugify(text: str, max_words: int = 6) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    words = text.split()[:max_words]
    slug = "-".join(words)
    slug = re.sub(r"-+", "-", slug).strip("-")
    return slug or "idea"


def report_path(report: Report, root: Path = IDEAS_DIR) -> Path:
    return root / f"{report.created.isoformat()}-{report.slug}.md"


def render_report(report: Report) -> str:
    lines: list[str] = []
    decision = report.decision
    score_avg = f"{decision.scores.average:.1f}/10" if decision else "n/a"
    rec = decision.recommendation if decision else "pending"

    lines.append("---")
    lines.append(f"title: {report.title}")
    lines.append(f"slug: {report.slug}")
    lines.append(f"date: {report.created.isoformat()}")
    lines.append(f"score: {score_avg}")
    lines.append(f"recommendation: {rec}")
    lines.append("---")
    lines.append("")
    lines.append(f"# {report.title}")
    lines.append("")
    lines.append(f"**Date:** {report.created.isoformat()}  ")
    lines.append(f"**Score:** {score_avg}  ")
    lines.append(f"**Recommendation:** {rec}")
    lines.append("")
    lines.append("## Idea")
    lines.append("")
    lines.append(report.idea.strip())
    lines.append("")

    if report.interview:
        lines.append("## Clarifying questions")
        lines.append("")
        for i, qa in enumerate(report.interview, 1):
            lines.append(f"**{i}. {qa.question.strip()}**")
            lines.append("")
            if qa.answered:
                lines.append(qa.answer.strip())
            else:
                lines.append("_(skipped)_")
            lines.append("")

    if report.market:
        lines.append("## Market analysis")
        lines.append("")
        lines.append(report.market.strip())
        lines.append("")

    if report.competitors:
        lines.append("## Competitor scan")
        lines.append("")
        lines.append(report.competitors.strip())
        lines.append("")

    if report.critiques:
        lines.append("## Multi-persona critique")
        lines.append("")
        for c in report.critiques:
            lines.append(f"### {c.name}")
            lines.append("")
            lines.append(c.text.strip())
            lines.append("")

    if report.synthesis:
        lines.append("### Synthesis")
        lines.append("")
        lines.append(report.synthesis.strip())
        lines.append("")

    if decision:
        lines.append("## Decision artifact")
        lines.append("")
        lines.append("### Scores (1-10)")
        lines.append("")
        s = decision.scores
        lines.append(f"- TAM: {s.tam}")
        lines.append(f"- Competitive density: {s.competitive_density}")
        lines.append(f"- Moat: {s.moat}")
        lines.append(f"- Founder-fit: {s.founder_fit}")
        lines.append(f"- Why-now timing: {s.why_now}")
        lines.append(f"- Capital efficiency: {s.capital_efficiency}")
        lines.append(f"- **Average: {s.average:.1f}/10**")
        lines.append("")
        lines.append("### Kill criteria")
        lines.append("")
        for k in decision.kill_criteria:
            lines.append(f"- {k.strip()}")
        lines.append("")
        lines.append("### Cheapest validation experiment")
        lines.append("")
        lines.append(decision.validation_experiment.strip())
        lines.append("")
        lines.append("### Recommendation")
        lines.append("")
        lines.append(f"**{decision.recommendation}** — {decision.rationale.strip()}")
        lines.append("")

    lines.append("---")
    lines.append(f"_Generated by idea-enhancer on {datetime.now().isoformat(timespec='seconds')}_")
    lines.append("")
    return "\n".join(lines)


def write_report(report: Report, root: Path = IDEAS_DIR) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    path = report_path(report, root)
    path.write_text(render_report(report), encoding="utf-8")
    return path


FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)


def parse_frontmatter(markdown: str) -> dict[str, str]:
    """Parse YAML-like frontmatter.  Uses ``partition`` so that values
    containing colons (URLs, ISO timestamps, etc.) are preserved.
    """
    m = FRONTMATTER_RE.match(markdown)
    if not m:
        return {}
    out: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            out[k.strip()] = v.strip()
    return out


def list_reports(root: Path = IDEAS_DIR) -> list[dict]:
    if not root.exists():
        return []
    out: list[dict] = []
    for path in sorted(root.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        meta = parse_frontmatter(text)
        meta["path"] = str(path)
        meta["body"] = text
        out.append(meta)
    return out
